CREATE TABLE IF NOT EXISTS user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    firstName TEXT NOT NULL,
    lastName TEXT NULL DEFAULT NULL,
    emailId TEXT NOT NULL,
    isActive TEXT NULL DEFAULT NULL
);